# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca9de9b037b3a4d2539da438fb6b23e3feef38333d820f58ff8e02d3904f3eea106b20d8d5f28b631c44ea1c1cb6bce315951e7762d1ebac365a22847923fec

test:
  secret_key_base: 47e80a4b1074d118037ecf5b65044814dced4d88e144bb87338aa1c1bebf4b0df7de943e150e88968bcd48c0e3f56527a1b79cef2b76857628670896a76e3eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
